# Generated by Django 5.2 on 2025-11-04 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=100)),
                ('managers', models.CharField(max_length=100)),
                ('company', models.CharField(max_length=50)),
                ('star_count', models.IntegerField(blank=True, null=True)),
                ('rating_shanghai', models.IntegerField(blank=True, null=True)),
                ('rating_zhaoshang', models.IntegerField(blank=True, null=True)),
                ('rating_jianxin', models.IntegerField(blank=True, null=True)),
                ('rating_morningstar', models.IntegerField(blank=True, null=True)),
                ('fee', models.FloatField(blank=True, null=True)),
                ('fund_type', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='InsuranceProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=50)),
                ('subcategory', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('coverage_summary', models.TextField()),
                ('payout_limit', models.CharField(max_length=100)),
                ('deductible_and_ratio', models.CharField(max_length=100)),
                ('base_premium', models.CharField(max_length=200)),
                ('tags', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='StockInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ts_code', models.CharField(max_length=20, unique=True)),
                ('symbol', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=50)),
                ('area', models.CharField(max_length=50)),
                ('industry', models.CharField(max_length=50)),
                ('list_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='StockDailyData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ts_code', models.CharField(max_length=20)),
                ('trade_date', models.DateField()),
                ('open', models.FloatField()),
                ('high', models.FloatField()),
                ('low', models.FloatField()),
                ('close', models.FloatField()),
                ('pre_close', models.FloatField()),
                ('change', models.FloatField()),
                ('pct_chg', models.FloatField()),
                ('vol', models.FloatField()),
                ('amount', models.FloatField()),
            ],
            options={
                'unique_together': {('ts_code', 'trade_date')},
            },
        ),
    ]
