# Generated by Django 5.2.7 on 2025-11-01 13:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Fund",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=10)),
                ("name", models.CharField(max_length=200)),
                ("fund_type", models.CharField(max_length=50)),
                (
                    "risk_level",
                    models.CharField(
                        choices=[
                            ("low", "低风险"),
                            ("medium", "中风险"),
                            ("high", "高风险"),
                        ],
                        max_length=20,
                    ),
                ),
                ("net_value", models.DecimalField(decimal_places=4, max_digits=10)),
                (
                    "daily_change",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
                ),
                ("week_change", models.DecimalField(decimal_places=2, max_digits=5)),
                ("month_change", models.DecimalField(decimal_places=2, max_digits=5)),
                ("manager", models.CharField(max_length=100)),
                ("establish_date", models.DateField()),
                ("scale", models.CharField(max_length=50)),
                ("description", models.TextField()),
                ("tags", models.JSONField(default=list)),
                ("features", models.JSONField(default=list)),
            ],
        ),
        migrations.CreateModel(
            name="Insurance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("insurance_type", models.CharField(max_length=50)),
                ("suitable_ages", models.CharField(max_length=50)),
                ("premium", models.DecimalField(decimal_places=2, max_digits=10)),
                ("coverage", models.TextField()),
                ("description", models.TextField()),
                ("tags", models.JSONField(default=list)),
                ("features", models.JSONField(default=list)),
            ],
        ),
        migrations.CreateModel(
            name="Stock",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=10)),
                ("name", models.CharField(max_length=100)),
                ("industry", models.CharField(max_length=50)),
                ("current_price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("change_rate", models.DecimalField(decimal_places=2, max_digits=5)),
                ("change_amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("market_cap", models.DecimalField(decimal_places=2, max_digits=15)),
                (
                    "pe_ratio",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "pb_ratio",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "dividend_yield",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                ("description", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="ClickHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("clicked_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "fund",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="recommendation.fund",
                    ),
                ),
                (
                    "insurance",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="recommendation.insurance",
                    ),
                ),
                (
                    "stock",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="recommendation.stock",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="StockHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("open_price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("close_price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("high_price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("low_price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("volume", models.BigIntegerField()),
                (
                    "stock",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="history_data",
                        to="recommendation.stock",
                    ),
                ),
            ],
            options={
                "ordering": ["-date"],
            },
        ),
        migrations.CreateModel(
            name="UserHolding",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quantity",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("purchased_at", models.DateTimeField(auto_now_add=True)),
                (
                    "fund",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="recommendation.fund",
                    ),
                ),
                (
                    "insurance",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="recommendation.insurance",
                    ),
                ),
                (
                    "stock",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="recommendation.stock",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("age", models.IntegerField()),
                ("occupation", models.CharField(max_length=100)),
                ("family_status", models.CharField(max_length=50)),
                (
                    "risk_tolerance",
                    models.CharField(
                        choices=[
                            ("low", "低风险"),
                            ("medium", "中风险"),
                            ("high", "高风险"),
                        ],
                        max_length=20,
                    ),
                ),
                ("total_assets", models.DecimalField(decimal_places=2, max_digits=15)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
